#include "life.h"
//Reads from the file generated by the MPI program and displays the slides using the curses library
int main() {
  FILE *fp;
  //Create a buffer for cells
  cell *buf;
  buf = (cell *)calloc(ROWNUM*COLNUM, sizeof(cell));

  void display(WINDOW *, cell *, int );
  //Child window
  WINDOW *win;
  //Initiate the screen functions
  initscr();
  cbreak();
  //Set a screen time out between each slide
  timeout(TIME_OUT);
  //Read the file once
  fp = fopen(FILENAME, "r");
  fseek(fp, SEEK_SET, 0);
  fread(buf, sizeof(cell), ROWNUM*COLNUM, fp);
  //Display the screen with the buf of the first slide
  display(stdscr, buf, ROWNUM*COLNUM);

  int counter = 1;
  //Read a character from window and repeat the process for all slides
  while(getch() != KEY_F(1) && counter < IMAGENUM) {
    fseek(fp, SEEK_SET, counter*ROWNUM*COLNUM);
    fread(buf, sizeof(cell), ROWNUM*COLNUM, fp);
    display(stdscr, buf, ROWNUM*COLNUM);
    counter++;
  }
  fclose(fp);
  free(buf);
  endwin();
  return 0;
}
//displays the slide, if a cells is alive it will put a '#' character on the screen at the right location of the cell
void display(WINDOW *win, cell *grid, int n)
{
	wclear(win);
	for(int i = 0; i < n; ++i)
			if(grid[i].newstate == TRUE)
				mvwaddch(win, grid[i].r, grid[i].c, CELL_CHAR);
	wrefresh(win);
}
